# Site wide configuration

title: Zigmund Kermish's Webpage
description: "Personal website of Zigmund Kermish"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://zkermish.github.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Zigmund Kermish
  web: http://zk.com
  email: zkermish@gmail.com
  twitter: zkermish
  bio: "A guy who likes cities, food, and building things for science"
  avatar: bio-photo.jpg # 160x160 px image for author byline
#  google:
#    plus: +MichaelRoseDesign
#    ad-client: ca-pub-7328585512091257
#    ad-slot: 3049671934
#  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
