# Site wide configuration

title: Zigmund Kermish's Webpage
description: "Personal website of Zigmund Kermish"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
#url: http://0.0.0.0:4000
url: http://zkermish.github.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap

flickr:
  api_key: a207e49f3ddb12a8fd31bce79a0f7ccc
  secret: 3dd75b019b4acc73
  user_id: 7366402@N03
  thumb_size: 'n'
  large_size: 'b'
  dir: 'photos'

# Site owner
owner:
  name: Zigmund Kermish
  web: http://zkermish.github.com
  email: zkermish@gmail.com
  twitter: zkermish
  bio: "A guy who likes cities, food, and building things for science"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +zkermish

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
